name: iOS CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Select Xcode version
      run: sudo xcode-select -switch /Applications/Xcode.app
      
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Build and test
      run: |
        xcodebuild test \
        -project TonalLab.xcodeproj \
        -scheme TonalLab \
        -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.6' \
        -enableCodeCoverage YES \
        CODE_SIGNING_ALLOWED=NO
